services:
  collector:
    build:
      dockerfile: server/Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - postgres
      - neo4j

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mongo
      - MONGODB_INITDB_ROOT_PASSWORD=password
      - MONGODB_INITDB_DATABASE=admin
    volumes:
      - ./databases/mongodb/data/db:/data/db
      - ./databases/mongodb/init.d/:/docker-entrypoint-initdb.d/

  postgres:
    container_name: postgres
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    volumes:
      - ./databases/postgres/data/db:/var/lib/postgresql/data
      - ./databases/postgres/init.d/:/docker-entrypoint-initdb.d/

  neo4j:
    container_name: neo4j
    image: neo4j:5.26.0
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
      - NEO4J_initial_dbms_default__database=sales
      - EXTENSION_SCRIPT=/script/import_data.sh
    volumes:
      - ./databases/neo4j/data/db:/data
      - ./databases/neo4j/data/plugins:/plugins
      - ./databases/neo4j/data/logs:/logs
      - ./databases/neo4j/import:/import
      - ./databases/neo4j/script:/script

